Web sockets adaptation for new database
Darderion/Modern-and-Magic-Chess-Online pull request #19
Opened 2022-07-25 18:10 UTC by toadharvard

2022-07-25 18:21 UTC, vs9h commented
После подтверждения от @Firsov62121 и @yakovypg можно будет принять

2022-07-25 18:30 UTC, yakovypg reviewed
Changes accepted

2022-07-25 18:42 UTC, Firsov62121 requested changes

2022-07-25 18:42 UTC, Firsov62121 commented on server/src/controllers/webSocket/gameMaster.js
>            this.isFinished = false;
Тут моя ошибка: нужно true.

2022-07-25 19:44 UTC, Firsov62121 commented on server/src/db/models/file.js
> +    static associate({ User, Style }) {}
Можно убрать {User, Style} отсюда.

2022-07-25 19:49 UTC, Firsov62121 commented on server/src/db/models/style.js
>        },
Мы вроде по типу фигуры, цвету и packName сможем восстановить src, а значит привязка к файлу вообще не нужна, если все стили хранить в виде /PackName/pieceColor/typeOfPiece.svg

2022-07-26 17:25 UTC, Firsov62121 approved these changes

2022-07-26 17:25 UTC, merged