Add inventory.
Darderion/Modern-and-Magic-Chess-Online pull request #22
Opened 2022-07-26 11:04 UTC by Firsov62121

Add inventory, add styles on server, add static support on server, add webSocketSuppert on server.

2022-07-26 11:57 UTC, vs9h commented on webapp/src/routes/Inventory/Inventory.jsx
> +};
Можно упростить так:
```js
const packs = ['go', 'br', 'default'];

const allFiguresWithStyles = Object.fromEntries(
	figures.map((figure) => [figure, packs]),
);

const stylesAll = Object.fromEntries(
	colors.map((color) => [color, allFiguresWithStyles]),
);
```
Как я понимаю это захардкоженные данные, которые потом будут доставаться с сервера, но всё же

2022-07-26 11:57 UTC, vs9h commented on webapp/src/routes/Inventory/Inventory.jsx
> +const imageSource = "http://localhost:5000/skins/";
Надо вынести в переменные окружения

2022-07-26 12:01 UTC, vs9h commented on webapp/src/routes/Inventory/Inventory.jsx
> +const imageSource = "http://localhost:5000/skins/";
И задать переменную `serverURL`, которая тут будет импортироваться.
Но эта переменная должна задаваться не тут (надо где-то создать файлик для таких переменных).

2022-07-26 12:07 UTC, vs9h commented on webapp/src/routes/Inventory/Inventory.jsx
> +  }
Такие функции лучше выносить в отдельный файл, чтобы потом каждый у себя в файликах их не определял. Ну и подобных функций много в библиотеке `lodash` есть, можно просто её подключить.

2022-07-26 12:08 UTC, vs9h commented on webapp/src/routes/Inventory/Inventory.jsx
> +    const [selectedStyle, changeStyle] = useState('default');
Общепринятое именование такое: `const [something, setSomething] = useState(...)`

2022-07-26 12:10 UTC, vs9h commented on webapp/src/routes/Inventory/Inventory.jsx
> +                            }} id={`${figure}__${color}__${stylesSelected[color][figure]}`}>
Это надо порефакторить
Во-первых длина строк огромная, линтер должен помогать в таких ситуациях
Во-вторых можно логику `onClick`, например, вынести в отдельную функцию повыше.

2022-07-26 18:14 UTC, vs9h commented on README.md
> +## React configuring
Client configuring

2022-07-26 18:16 UTC, vs9h commented on README.md
> +2) Run `yarn install`
Move to `install_web.sh`.
And union `Web-Server configuring` and `React configuring` in `Web-app configuring`
Then write how to start web-server and client-server

2022-07-26 18:19 UTC, vs9h commented on webapp/src/config/index.js
> +const exp = {
rename to `config` or 
```js
export default { server: { ... } }
```

2022-07-26 19:19 UTC, vs9h requested changes
Обсудили замечания в дискорде (переделать `README.md`, `Inventory.jsx`, ...)

2022-07-26 20:10 UTC, Darderion approved these changes, later dismissed

2022-07-26 20:10 UTC, Darderion commented on webapp/.env.example
> +REACT_APP_SERVER_STYLE_FOLDER=skins
https://thoughtbot.com/blog/no-newline-at-end-of-file

2022-07-26 20:10 UTC, Darderion commented on webapp/src/routes/Inventory/Inventory.jsx
> +const figures = ['bishop', 'king', 'knight', 'queen', 'pawn', 'rook'];
Enum for pieces

2022-07-26 20:10 UTC, Darderion commented on webapp/src/routes/Inventory/Inventory.jsx
> +const colors = ['black', 'white'];
Enum for sides

2022-07-26 20:23 UTC, vs9h commented on webapp/src/routes/Inventory/Inventory.jsx
> +const figures = ['bishop', 'king', 'knight', 'queen', 'pawn', 'rook'];
Что подразумевается под енамами?

2022-07-26 22:17 UTC, vs9h commented on webapp/src/routes/Inventory/Inventory.jsx
> +}
Вынести в `components`

2022-07-26 22:18 UTC, vs9h commented on webapp/package.json
> +    "dotenv": "^16.0.1",
Убрать

2022-07-26 22:19 UTC, vs9h commented on webapp/src/routes/Lobby/lobbyInfo.js
> +export default LobbyInfo;
Этот файлик кажется не нужен (есть `routes/Inventory/lobbyInfo.js`)

2022-07-26 22:25 UTC, vs9h commented on webapp/src/routes/Inventory/Inventory.jsx
> +const colors = ['black', 'white'];
@Darderion, как это должно выглядеть?
Мы один раз задали эти значения, дальше нам никогда не нужно будет их явно задавать через строки. Не до конца понятно что именно вы выиграем.
То, что указано на 11-28 строках это данные, которые в будущем будут прилетать с сервера.

2022-07-27 01:40 UTC, Darderion commented on webapp/src/routes/Lobby/lobbyInfo.js
> +export default LobbyInfo;
Другое lobbyInfo- не класс, а функция, возвращающая объект, так что предпочтительно оставить этот файл и убрать тот, который лежит в Inventory

2022-07-27 01:56 UTC, Darderion commented on webapp/src/routes/Inventory/Inventory.jsx
> +const colors = ['black', 'white'];
Желательно куда-то вынести этот массив или же используемые строки, так как люди повторно выписывают названия фигур в разных местах (https://github.com/Darderion/Modern-and-Magic-Chess-Online/blob/3f7b7022a84e9bc2f9c4df11e320a096c6c25832/webapp/src/routes/Board%20%5Btesting%5D/BoardComponent.jsx)
Если для фигур будут объявлены значения, то это позволит обеспечить единообразие строковых представлений фигур по всей кодовой базе, а также исключит опечатки и несоответствия значений для различных вызовов API, если кто-то решит использовать для своего модуля другое написание или же множественное число для обозначения типа фигуры

2022-07-27 09:32 UTC, Darderion approved these changes, later dismissed

2022-07-27 10:24 UTC, vs9h approved these changes, later dismissed

2022-07-27 10:30 UTC, vs9h commented on webapp/src/routes/Lobby/lobbyInfo.js
> +export default LobbyInfo;
А почему в данном случае класс предпочтительнее? Это же просто функция (класс), которая будет использоваться пока нет возможности получить данные с сервера. Кажется в данном случае без разницы.

2022-07-27 11:26 UTC, vs9h approved these changes

2022-07-27 11:27 UTC, merged