Connector
Darderion/Modern-and-Magic-Chess-Online pull request #23
Opened 2022-07-26 17:56 UTC by Pechenux

2022-07-26 19:45 UTC, vs9h requested changes
Обсудили в дискорде (порефакторить `connector.js`)

2022-07-26 20:07 UTC, Darderion submitted a review, later dismissed

2022-07-26 20:07 UTC, Darderion commented on webapp/src/Connector.js
> +        ws.current = new WebSocket("ws://localhost:5000/main");
Env.URL

2022-07-26 20:07 UTC, Darderion commented on webapp/src/Connector.js
> +    }
Empty function without TODO or comments

2022-07-26 20:07 UTC, Darderion commented on server/src/server.js
> +});
https://thoughtbot.com/blog/no-newline-at-end-of-file

2022-07-27 11:56 UTC, Pechenux commented on webapp/src/Connector.js
> +        ws.current = new WebSocket("ws://localhost:5000/main");
Пока что в конфигах генерируется неправильный адрес. Я записал эту проблему в todo

2022-07-27 12:44 UTC, Pechenux commented on webapp/src/Connector.js
> +        ws.current = new WebSocket("ws://localhost:5000/main");
Добавил в конфиг свой путь до вебсокетов, сейчас всё работает

2022-07-28 10:01 UTC, vs9h approved these changes

2022-07-28 10:31 UTC, merged